/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-05-17 21:44:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.catalogos.materia;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AgregaArchivos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out = _jspx_page_context.pushBody();
      out.write("<script src=\"js/materia/AgregaArchivos.js\"></script>\t\t\n");
      out.write("\t\t<section style=\"clear: both\" >\n");
      out.write("\t        <form action=\"AgregaFile\" method=\"post\" name=\"form1\" id=\"form1\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t            <div style=\"text-align: center; margin-bottom: 30px;\">    \n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-widget\" id=\"message\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui-state-highlight ui-corner-all msg\" >\n");
      out.write("\t\t\t\t\t\t\t\t<p><span class=\"ui-icon ui-icon-info\" style=\"float: left; margin-right: .3em;\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<strong id=\"innerMessage\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</strong></p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t                <h3>Agregar Archivos</h3>\n");
      out.write("\t\t                <table class=\"list1 green\" style=\"width:60%25\">   \n");
      out.write("\t\t                \t<tr>\n");
      out.write("\t\t           \t            <th width=\"15%25\" class=\"right\">Clave</th>\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%25\" class=\"left\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.cveMat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"15%25\" class=\"right\">Modulo</th>\n");
      out.write("\t\t                        <td width=\"35%25\" class=\"left\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.modulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\t\n");
      out.write("\t\t                    </tr>\n");
      out.write("\t\t                    <tr>\n");
      out.write("\t\t                        <th class=\"right\">Nombre</th>\n");
      out.write("\t\t                        <td class=\"left\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.nomMat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\n");
      out.write("\t\t                        <th class=\"right\">Unidad</th>\n");
      out.write("\t\t                        <td class=\"left\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.unidad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\n");
      out.write("\t\t                    </tr>\n");
      out.write("\t\t                    <tr>\n");
      out.write("\t\t                       \t<th class=\"right\">Nivel</th>\n");
      out.write("\t\t                        <td class=\"left\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.nomNivel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.nomNivelGrado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\n");
      out.write("\t\t                       \t<th class=\"right\">Contenido</th>\n");
      out.write("\t\t                        <td class=\"left\">\n");
      out.write("\t                        \t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contenido.parentContName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("\t                        \t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contenido.caption}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("\t\t                        </td>\n");
      out.write("\t\t                    </tr>\n");
      out.write("\t\t\t            </table>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t             <div style=\"text-align: center\">\n");
      out.write("\t\t                 <div style=\"margin-bottom:20px\">\n");
      out.write("\t\t                 \t<input type=\"file\" name=\"file\" id=\"file\" multiple=\"multiple\" onchange=\"funcEligirTipo()\">\n");
      out.write("\t\t                 </div>\n");
      out.write("\t\t          \t\t <div style=\"margin-bottom:20px\">Tipo del archivo: \n");
      out.write("\t\t\t          \t\t<select name=\"tipoArchivo\" id=\"tipoArchivo\" onchange=\"\">\n");
      out.write("\t\t\t                    <option value=\"0\">----------</option>\n");
      out.write("\t\t         \t            <option value=\"1\">Imagen</option>\n");
      out.write("\t\t         \t            <option value=\"2\">Animacion</option>\n");
      out.write("\t\t         \t            <option value=\"9\">Html5</option>\n");
      out.write("\t\t         \t            <option value=\"3\">Sonido</option>\n");
      out.write("\t\t         \t            <option value=\"4\">Actividades</option>\n");
      out.write("\t\t         \t            <option value=\"5\">Actividades Complementarias</option>\n");
      out.write("\t\t         \t            <option value=\"6\">Contenido Imprimible</option>\n");
      out.write("\t\t         \t            <option value=\"7\">Programa Imprimible</option>\n");
      out.write("\t\t         \t            <option value=\"8\">Formulario</option>\n");
      out.write("\t\t\t                </select>\n");
      out.write("\t\t\t\t\t\t </div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-bottom: 10px\">Nota: El tamaño máximo del archivo es 600KB</div> \n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-bottom:10px\">\n");
      out.write("\t\t\t                <input type=\"button\" value=\"Agregar\" class=\"botonimagenchico\" onclick=\"funcAgregar()\" />\n");
      out.write("\t\t\t                <input type=\"button\" value=\"Cerrar\" class=\"botonimagenchico\" onclick=\"funcCerrar()\"/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"Agregar Html5\" class=\"botonimagenchico\" onclick=\"funcAgregarHtml5()\" />\n");
      out.write("\t\t                </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <input type=\"hidden\" id=\"hiddenCveMat\" name=\"hiddenCveMat\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.cveMat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\n");
      out.write("\t\t            <input type=\"hidden\" id=\"hiddenCveCont\" name=\"hiddenCveCont\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contenido.menuItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"hiddenTipo\" name=\"hiddenTipo\" value=\"\"/>\t        \n");
      out.write("\t\t\t</form>\n");
      out.write("        </section>");
      java.lang.String _jspx_temp0 = ((javax.servlet.jsp.tagext.BodyContent)out).getString();
      out = _jspx_page_context.popBody();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Master.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Agregar Archivo", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("mostrarMenu", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("false", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("content", request.getCharacterEncoding())+ "=" + _jspx_temp0, out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
